name: Copy build to root

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  copy-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Copy build contents to root
      run: |
        cp -r build/* .
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m "Copy build contents to root directory"
        git push
